### ISSUE TITLE
Import history from NeLS is not completing

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#41]
The import of (a very small) history from NeLS is not completing. It is important to get this working before the series of online training events we will give in March
<img width="315" alt="Screenshot 2021-02-17 at 12 50 45" src="https://user-images.githubusercontent.com/18656531/108200619-fe0aa480-711e-11eb-8efa-af8f423b2bd6.png">

**Comment by bruggerk** [comment]
Is this test or dev? 
I will look at it this week.
/Kim

**Comment by ehj000** [comment]
It is on dev. Thanks

**Comment by kjellp** [comment]
Do you mean prod instead of dev? (i.e. not test, but the other one => prod)

I posted a few observations from prod (which I assumed) in the #usegalaxy channel earlier today:
![Screenshot from 2021-02-17 16-18-00](https://user-images.githubusercontent.com/4224894/108224961-bfcfae00-713b-11eb-9021-37897e6961dd.png)

**Comment by ehj000** [comment]
sorry, meant prod

**Comment by bruggerk** [comment]
Test was down as well (for a different reason)

Test is till using prod nels storage, but the test one was/is(?) down
so I am not touching it for now.

Secondly it has been fixed for both instances, it should pick up and
run your import, 

Let me know if the problem presists

/Kim

**Comment by ehj000** [comment]
Perfect, thank you
<img width="316" alt="Screenshot 2021-02-18 at 10 59 21" src="https://user-images.githubusercontent.com/18656531/108340006-67022300-71d8-11eb-8ff7-6559dac692fe.png">
