### ISSUE TITLE
Barplot fails

### ISSUE THREAD

**Issue by ehj000** [usegalaxy-no/galaxyadmin#58]
This error looks familiar. Anyone knows how to fix this: gnuplot: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by kjetilkl** [comment]
This tool only has one listed requirement: `gnuplot-py` (which also depends on `gnuplot).` 
I tried to build the container manually but got the same error. However, when I placed Bioconda before Conda-forge in the channels list and tried building it again, it complained about missing the shared library `libjpeg.so.8` instead. The container in [BioContainers](https://biocontainers.pro/) has similar issues, so using that didn't work either. Finally, I managed to solve it by adding a symlink from the file `libjpeg.so.9` to `libjpeg.so.8` inside the container. At least you now get plots that are just as ugly as those made by UseGalaxy.eu, but even though output is produced, the job ends in a red error state since the tool complains about a missing font to STDERR. This could probably be suppressed to get a green job state instead, but that will require modifications to the tool wrapper.

**Comment by kjetilkl** [comment]
I hacked the "bar_chart.xml" tool wrapper (which comes bundled with Galaxy in the "tools/plotting" directory) and added a `profile="16.04"` attribute to the `<tool>` element. This ensures that Galaxy no longer automatically treats output to STDERR by this tool as a sign of failure. However, since the hack was done directly in Galaxy code, I'm not sure if it will persists, and a better solution is desirable. Also, the font is still ugly (but similar to UseGalaxy.eu).

**Comment by ehj000** [comment]
The tools works, and yes, the plots are not eye candy. Thanks again Kjetil
