### ISSUE TITLE
Tool job error for week 10, 2022

### ISSUE THREAD

**Issue by tothuhien** [usegalaxy-no/galaxyadmin#66]
So far I've seen 1 tool exited with error that is not due to user mistakes: [MiRDeep2 Mapper](https://usegalaxy.no/root?tool_id=toolshed.g2.bx.psu.edu/repos/rnateam/mirdeep2_mapper/rbc_mirdeep2_mapper/2.0.0)
Job Id: [149690](https://usegalaxy.no/reports/jobs/job_info?f-state=error&f-specified_date=2022-03-08&sort=id&operation=job_info&id=e2042b627d4dd0dd&webapp=reports&sort_id=default&order=default)
_Error: ...tool_script.sh: mapper.pl: not found_
The requirement package mirdeep2's version is specified to 2.0.0.8 which is only for osx. Do we need to install new container for it?

**Comment by kjetilkl** [comment]
Thanks for the report!
I think the problem was that we had an old tool wrapper which required old-style tool shed packages of mirDeep2 mapper 2.0, bowtie 0.12.7 and perl 5.18.1. None of these were available from Conda. I uninstalled this version and installed the latest version instead, which requires mirDeep2=2.0.0.8. That worked!
