### ISSUE TITLE
SignalP tool fails to install

### ISSUE THREAD

**Issue by tothuhien** [usegalaxy-no/galaxyadmin#78]
A user reported that a job of SignalP did not start from Saturday, with message "The job is waiting to run". The tool hasn't been run before, so there may be problem with the installation.

**Comment by tothuhien** [comment]
The tool requires 'signalp' package which is only available in 'predector' Conda channel.  Maybe it's not one of the default conda channels?

**Comment by kjetilkl** [comment]
The "signalp" package in the "predector" channel is a bit strange. Even if you install it via Conda, you still have to download "signalp" as a tarball from the original web site and then use a script in the Conda package to _register_ your installation and unpack the tarball. I think this has to do with the license of the program, since you have to fill in your name and affiliation and check off "I agree" on the license agreement when submitting. This will give you a temporary URL you can use to download the actual program. So, even if we had added the "predector" Conda channel in Galaxy, the automatic container build step would still have failed.

**Comment by kjetilkl** [comment]
Well, this has certainly been an exciting, weeklong trip into the dark pits of dependency hell. I belive I have fixed `SignalP` now, and also 4 other tools in the same suite: `Promoter 2.0`, `TMHMM 2.0`, `RXLR Motifs` and `WoLF PSORT`. For the last tool, `psort`, I think I have managed to install all the dependencies into the container, but it fails with some Perl issues. Unless someone actually needs to run `psort`, I will just leave it as is for now rather than waste more time on it.

**Comment by tothuhien** [comment]
Thanks @kjetilkl , I will inform the user about this 👍

**Comment by sveinugu** [comment]
> Well, this has certainly been an exciting, weeklong trip into the dark pits of dependency hell.

Sorry to hear about that. I hope you have emerged on the other side relatively sane. Best wishes for your recovery - I do think your scars will heal eventually! 🤕
